FROM node:22.7.0

ENV CI=true

RUN mkdir -p /usr/src/app/frontend/
WORKDIR /usr/src/app/

COPY package.json /usr/src/app/
RUN npm install

COPY ./assets/ /usr/src/app/frontend/
COPY ./components/ /usr/src/app/frontend/
COPY ./pages/ /usr/src/app/frontend/
COPY ./public/ /usr/src/app/frontend/
COPY ./server/ /usr/src/app/frontend/
COPY ./app.vue /usr/src/app/frontend/
COPY ./nuxt.config.ts /usr/src/app/frontend/
COPY ./tsconfig.json /usr/src/app/frontend/
COPY ./.env /usr/src/app/

EXPOSE 80
EXPOSE 3000

CMD [ "npm", "run", "dev" ]
