#!/bin/bash

if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 [email] [password]"
    exit 1
fi

SUDO_ACCESS=""

if [ $(test -r /var/run/docker.sock; echo "$?") -ne 0 ]; then
    SUDO_ACCESS="sudo"
fi

$SUDO_ACCESS docker run -it --rm -v $(pwd)/:/app/ -v $(pwd)/data/images/:/usr/src/app/images/ --env-file ./frontend/.env -e REMOTE_API_EMAIL="$1" -e REMOTE_API_PASSW="$2" --network soul-connection --ip 172.20.0.11 --name soul-connection-add_user node:22.7.0 bash -c "cd /app/ && npm install && node /app/backend/utils/addUser.js"