services:
  db:
    image: mysql:9.0.1
    env_file:
      - ./frontend/.env
    container_name: soul-connection-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      soul-connection:
        ipv4_address: ${DB_HOST}
    volumes:
      - "./data/db/:/var/lib/mysql"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: soul-connection-backend
    restart: always
    environment:
      LOCAL_PORT: ${BACK_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      soul-connection:
        ipv4_address: ${BACK_HOST}
    volumes:
      - "./data/images/:/usr/src/app/images/"
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend/
  #   env_file:
  #     - ./frontend/.env
  #   container_name: soul-connection-frontend
  #   restart: always
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     API_BASE_URL: ${LOCAL_API_BASE_URL}
  #     PORT: ${FRONT_PORT}
  #   networks:
  #     soul-connection:
  #       ipv4_address: ${FRONT_HOST}
  #   ports:
  #     - "${FRONT_PORT}:${FRONT_PORT}"
  #   depends_on:
  #     - db
  #     - backend

  # fetch:
  #   image: node:22.7.0
  #   env_file:
  #     - ./frontend/.env
  #   container_name: soul-connection-fetch
  #   restart: always
  #   environment:
  #     REMOTE_API_KEY: ${REMOTE_API_KEY}
  #     REMOTE_API_EMAIL: ${REMOTE_API_EMAIL}
  #     REMOTE_API_PASSW: ${REMOTE_API_PASSW}
  #     DB_HOST: ${DB_HOST}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     DB_NAME: ${DB_NAME}
  #   entrypoint: bash -c "cd /app/ && npm install && node /app/backend/utils/fetch.js"
  #   volumes:
  #     - "./data/images/:/usr/src/app/images/"
  #     - "./:/app/"
  #   networks:
  #     soul-connection:
  #       ipv4_address: ${FETCH_HOST}
  #   depends_on:
  #     - db

networks:
  soul-connection:
    external: true
    name: soul-connection
