#!/bin/bash

SUDO_ACCESS=""

if [ $(test -r /var/run/docker.sock; echo "$?") -ne 0 ]; then
    SUDO_ACCESS="sudo"
fi

export $(cat ./frontend/.env | xargs)

if ! ping -c 1 $DB_HOST >/dev/null; then
    echo "DB Host ($DB_HOST) seems offline"
    echo "You can either try & connect anyway (Press Enter) or stop now (Ctrl+C)"
    read -p "(Softlock protection) > "
fi

$SUDO_ACCESS docker run -it --rm -v ./:/app/ -v ./data/images/:/usr/src/app/images/ --env-file ./frontend/.env --network soul-connection --ip 172.20.0.6 --name soul-connection-fetch node:22.7.0 node /app/backend/utils/fetch.js

sudo chown $USER:$USER -R ./data/images/

cp default.png ./data/images/