#!/bin/bash

# The followin will define the status of run, as well as PORT used
STATUS="dev" # "dev" / "prod"

DC_COMMAND="docker-compose"
SUDO_ACCESS=""

if [ $(test -r /var/run/docker.sock; echo "$?") -ne 0 ]; then
    SUDO_ACCESS="sudo"
fi

if ! command -v $DOCKER_COMMAND$DC_COMMAND &> /dev/null
then
    DC_COMMAND="docker compose"
fi

$SUDO_ACCESS docker stop soul-connection-db soul-connection-backend soul-connection-frontend
$SUDO_ACCESS docker rm soul-connection-db soul-connection-backend soul-connection-frontend

$SUDO_ACCESS docker network rm soul-connection
$SUDO_ACCESS docker network create --gateway 172.20.0.1 --subnet 172.20.0.0/24 soul-connection
$SUDO_ACCESS docker rmi epitech-soul-connection-backend epitech-soul-connection-frontend

./scripts/read_env.py > ./frontend/.env || exit 1

export $(cat ./frontend/.env | xargs)

if [ "$STATUS" = "prod" ]; then
    export PORT=$FRONT_PROD_PORT
else
    export PORT=$FRONT_DEV_PORT
fi

$SUDO_ACCESS bash -c "export $(cat ./frontend/.env | xargs) STATUS=$STATUS PORT=$PORT && $DC_COMMAND up"

rm ./frontend/.env
