name: Feature request
description: Request a feature
labels: [feature]
body:

  - type: markdown
    attributes:
      value: |
        Before requesting: search existing feature requests and be sure you are not requesting an already existing feature.

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved. Include references to other projects if relevant."
      placeholder: "No images of nian cat available. Please add because..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem? Is it worth the cost?"
    validations:
      required: true