#!/bin/bash

DB_HOST=172.20.0.2
DB_USER=root
DB_PASS=cf8337a841ce8088aef49d9bedb0655c5f5f4ef7e2f0d5d9bec280611a603faf
DB_NAME=soul_connection

DEV_DB_PORT=3306

DEV_BACK_PORT=3000
BACK_PORT=80

SECRET_KEY=c2f7bdab992343c995bad42153eb3bf6d44e6580f7ecf86457ec3cbac9e0bc3c

variables=("DB_HOST" "DB_USER" "DB_PASS" "DB_NAME" "DEV_DB_PORT" "DEV_BACK_PORT" "BACK_PORT" "SECRET_KEY")

for var in "${variables[@]}"; do
    value="${!var}"
    echo "$var=$value"
done

echo "DATABASE_URL=mysql://$DB_USER:$DB_PASS@$DB_HOST:3306/$DB_NAME"