name: Mirror project to School repo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  mirror:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror repository to target repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.TARGET_REPOSITORY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
